"""Backwards-compatibility shim — import from ``QDMpy.fitting.guess`` instead."""
from QDMpy.fitting.guess import (
    DEFAULT_VMAX,
    DEFAULT_VMIN,
    PROMINENCE,
    get_model_by_peaks,
    guess_center,
    guess_center_pixel,
    guess_contrast,
    guess_contrast_pixel,
    guess_initial_fit_parameters,
    guess_model,
    guess_n_peaks,
    guess_width,
    guess_width_pixel,
    normalize_pixel,
    validate_array,
)

__all__ = [
    "DEFAULT_VMAX",
    "DEFAULT_VMIN",
    "PROMINENCE",
    "get_model_by_peaks",
    "guess_center",
    "guess_center_pixel",
    "guess_contrast",
    "guess_contrast_pixel",
    "guess_initial_fit_parameters",
    "guess_model",
    "guess_n_peaks",
    "guess_width",
    "guess_width_pixel",
    "normalize_pixel",
    "validate_array",
]
